<?php

return [
    'plans' => [
        'FREE' => [
            'code' => 'FREE',
            'name' => 'Free',
            'amount' => 0,
            'currency' => 'IDR',
            'guest_limit' => 50,
            'photo_limit' => 100,
            'retention_days' => 7,
            'zip_download' => false,
            'google_photos' => false,
            'staff_limit' => 1,
            'branding' => 'BRANDED',
            'single_photo_download' => true,
            'popular' => false,
        ],
        'BASIC' => [
            'code' => 'BASIC',
            'name' => 'Basic',
            'amount' => 99000,
            'currency' => 'IDR',
            'guest_limit' => 300,
            'photo_limit' => 1000,
            'retention_days' => 30,
            'zip_download' => true,
            'google_photos' => false,
            'staff_limit' => 2,
            'branding' => 'SMALL',
            'single_photo_download' => true,
            'popular' => false,
        ],
        'PREMIUM' => [
            'code' => 'PREMIUM',
            'name' => 'Premium',
            'amount' => 249000,
            'currency' => 'IDR',
            'guest_limit' => 1000,
            'photo_limit' => 5000,
            'retention_days' => 90,
            'zip_download' => true,
            'google_photos' => true,
            'staff_limit' => 5,
            'branding' => 'NONE',
            'single_photo_download' => true,
            'popular' => true,
        ],
    ],

    'provider' => [
        'base_url' => env('PAYMENT_ADAPTER_URL', env('PAY_BASE_URL', 'https://pay.proyek.org')),
        'project_code' => env('PAYMENT_ADAPTER_PROJECT_CODE', env('PAY_PROJECT_CODE')),
        'api_key' => env('PAYMENT_ADAPTER_API_KEY', env('PAY_API_KEY')),
        'webhook_secret' => env('PAYMENT_ADAPTER_WEBHOOK_SECRET', env('PAY_WEBHOOK_SECRET')),
        'timeout' => (int) env('PAYMENT_ADAPTER_TIMEOUT', env('PAY_TIMEOUT', 10)),
        'webhook_tolerance_seconds' => (int) env('PAYMENT_ADAPTER_WEBHOOK_TOLERANCE_SECONDS', env('PAY_WEBHOOK_TOLERANCE_SECONDS', 300)),
    ],
];
